{% set version = '2.0.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lintr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lintr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lintr/lintr_{{ version }}.tar.gz
  sha256: fe0723757b653ef83ec7a5005d0a7524cd917d646d35a5627ee639158881ce93

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rmarkdown, mockery
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-codetools
    - r-crayon
    - r-cyclocomp
    - r-digest
    - r-httr >=1.2.1
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-testthat >=2.2.1
    - r-xml2 >=1.0.0
    - r-xmlparsedata >=1.0.3

  run:
    - r-base
    - r-codetools
    - r-crayon
    - r-cyclocomp
    - r-digest
    - r-httr >=1.2.1
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-testthat >=2.2.1
    - r-xml2 >=1.0.0
    - r-xmlparsedata >=1.0.3

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lintr')"           # [not win]
    - "\"%R%\" -e \"library('lintr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/jimhester/lintr
  license: MIT
  summary: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports
    on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime
    Text' and 'Atom'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid
    - demo

# The original CRAN metadata for this package was:

# Package: lintr
# Title: A 'Linter' for R Code
# Version: 2.0.1
# Authors@R: c( person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre")), person("Florent", "Angly", role = "aut"), person("Russ", "Hyde", role = "aut") )
# URL: https://github.com/jimhester/lintr
# BugReports: https://github.com/jimhester/lintr/issues
# Description: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime Text' and 'Atom'.
# Depends: R (>= 3.2)
# Imports: rex, crayon, codetools, cyclocomp, testthat (>= 2.2.1), digest, rstudioapi (>= 0.2), httr (>= 1.2.1), jsonlite, knitr, stats, utils, xml2 (>= 1.0.0), xmlparsedata (>= 1.0.3)
# Suggests: rmarkdown, mockery
# License: MIT + file LICENSE
# LazyData: true
# Encoding: UTF-8
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# Collate: 'T_and_F_symbol_linter.R' 'utils.R' 'aaa.R' 'actions.R' 'addins.R' 'assignment_linter.R' 'cache.R' 'closed_curly_linter.R' 'commas_linter.R' 'comment_linters.R' 'comments.R' 'cyclocomp_linter.R' 'declared_functions.R' 'object_name_linters.R' 'deprecated.R' 'equals_na_lintr.R' 'exclude.R' 'expect_lint.R' 'extract.R' 'extraction_operator_linter.R' 'function_left_parentheses.R' 'get_source_expressions.R' 'ids_with_token.R' 'implicit_integer_linter.R' 'infix_spaces_linter.R' 'line_length_linter.R' 'lint.R' 'methods.R' 'namespace.R' 'no_tab_linter.R' 'object_usage_linter.R' 'open_curly_linter.R' 'paren_brace_linter.R' 'path_linters.R' 'pipe_continuation_linter.R' 'semicolon_terminator_linter.R' 'seq_linter.R' 'settings.R' 'single_quotes_linter.R' 'spaces_inside_linter.R' 'spaces_left_parentheses_linter.R' 'trailing_blank_lines_linter.R' 'trailing_whitespace_linter.R' 'tree-utils.R' 'undesirable_function_linter.R' 'undesirable_operator_linter.R' 'unneeded_concatenation_linter.R' 'with_id.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2020-02-18 21:46:51 UTC; jhester
# Author: Jim Hester [aut, cre], Florent Angly [aut], Russ Hyde [aut]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-02-19 06:00:13 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
